"use client";
import "./globals.css";
import { ThemeProvider, CssBaseline } from "@mui/material";
import { darkTheme } from "./theme/themes";
import Navbar from "./Compoents/Navbar/Navbar";
import { useState } from "react";


export default function RootLayout({ children }: { children: React.ReactNode }) {
  const [toggleDark, settoggleDark] = useState(false);

  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>

      <ThemeProvider theme={darkTheme}>
        <CssBaseline />
        <body>
        <Navbar />

          {children}
          </body>
      </ThemeProvider>
    </html>
  );
}
